#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be: 
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.


million = 1000000

def fib():
    current = 0
    after = 1
    total = 0
    while current < 4 * million:
        current, after = after, current + after
        if not (current % 2):
            total += current  
    return total 




print fib()

